import { useCallback,useEffect,useMemo,useState,type FormEvent } from "react";
import type { SupabaseClient } from "@supabase/supabase-js";
import { createFantasyLeague,getFantasyOverview,getMyFantasyLeagues,joinFantasyLeague,setFantasyPreferences,startFantasyDraft,submitFantasyPick,submitFantasyWaiver,type FantasyFeatureState,type FantasyLeague,type FantasyOverview } from "../fantasyStore";
import { createSupabaseSnackSearch,saveSelectedSnack,type SnackMetadata } from "../snackMetadata";
import { friendlyError } from "../errors";

type Props={client:SupabaseClient;currentUserId:string;feature:FantasyFeatureState};
export function FantasyScreen({client,currentUserId,feature}:Props){
  const[leagues,setLeagues]=useState<FantasyLeague[]>([]);const[selectedId,setSelectedId]=useState("");const[overview,setOverview]=useState<FantasyOverview|null>(null);const[error,setError]=useState("");const[busy,setBusy]=useState(false);const[leagueName,setLeagueName]=useState("");const[joinCode,setJoinCode]=useState("");const[query,setQuery]=useState("");const[results,setResults]=useState<SnackMetadata[]>([]);const[preferences,setPreferences]=useState<SnackMetadata[]>([]);const[waiverOut,setWaiverOut]=useState("");
  const load=useCallback(async()=>{if(!feature.enabled)return;try{const next=await getMyFantasyLeagues(client);setLeagues(next);const id=selectedId||next[0]?.id||"";setSelectedId(id);setOverview(id?await getFantasyOverview(client,id):null);setError("");}catch(e){setError(friendlyError(e));}},[client,feature.enabled,selectedId]);
  useEffect(()=>{void load();},[load]);
  const search=useMemo(()=>createSupabaseSnackSearch(client,(_q,items)=>setResults(items),()=>setError("Remote search is unavailable; known snacks still work.")),[client]);
  useEffect(()=>()=>search.dispose(),[search]);useEffect(()=>{if(query.trim().length<2){setResults([]);return;}void search.search(query);},[query,search]);
  if(!feature.enabled)return <LockedFantasy feature={feature}/>;
  const selectedLeague=leagues.find(x=>x.id===selectedId);const season=overview?.season;const managers=overview?.draftOrder.length||0;const round=season&&managers?Math.floor((season.currentPick-1)/managers)+1:0;const within=season&&managers?(season.currentPick-1)%managers+1:0;const pickerPosition=round%2===1?within:managers-within+1;const pickerId=overview?.draftOrder.find(x=>x.position===pickerPosition)?.userId;const myTurn=season?.status==="drafting"&&pickerId===currentUserId;
  async function act(work:()=>Promise<unknown>){setBusy(true);try{await work();setQuery("");await load();}catch(e){setError(friendlyError(e));}finally{setBusy(false);}}
  async function create(event:FormEvent){event.preventDefault();await act(async()=>{const rows=await createFantasyLeague(client,leagueName);setSelectedId(rows[0].league_id);setLeagueName("");});}
  async function join(event:FormEvent){event.preventDefault();await act(async()=>{const id=await joinFantasyLeague(client,joinCode);setSelectedId(id);setJoinCode("");});}
  async function submitSearch(event:FormEvent){event.preventDefault();if(query.trim().length<3)return;setBusy(true);await search.searchRemote(query);setBusy(false);}
  async function choose(snack:SnackMetadata,mode:"pick"|"preference"|"waiver"){const id=snack.id||await saveSelectedSnack(client,snack);if(mode==="preference"){if(!preferences.some(x=>(x.id||x.barcode)===id))setPreferences([...preferences,{...snack,id}]);return;}if(!season)return;if(mode==="waiver"){if(!waiverOut)return setError("Choose the roster snack you are replacing.");await act(()=>submitFantasyWaiver(client,season.id,waiverOut,id));}else await act(()=>submitFantasyPick(client,season.id,id));}
  return <div className="fantasy-screen"><header className="fantasy-hero"><p className="section-label">Monthly fantasy</p><h1>Draft your snack shelf.</h1><p>Five categories. Exclusive picks. Everyone else’s activity scores for you.</p></header>{error?<div className="error-message" role="alert">{error}</div>:null}
    {!leagues.length?<section className="fantasy-onboarding"><form onSubmit={create}><h2>Create a league</h2><label>League name<input value={leagueName} onChange={e=>setLeagueName(e.target.value)} required/></label><button className="primary-button" disabled={busy}>Create league</button></form><form onSubmit={join}><h2>Join with a code</h2><label>Join code<input value={joinCode} onChange={e=>setJoinCode(e.target.value)} required/></label><button className="secondary-button" disabled={busy}>Join league</button></form></section>:<>
      <div className="league-switcher"><label>League<select value={selectedId} onChange={e=>setSelectedId(e.target.value)}>{leagues.map(l=><option value={l.id} key={l.id}>{l.name}</option>)}</select></label>{selectedLeague?<span><b>{selectedLeague.memberCount}/8 managers</b><small>Code {selectedLeague.joinCode}</small></span>:null}</div>
      {!season?<section className="draft-lobby"><div><h2>Draft lobby</h2><p>Four managers and enough catalog depth are required before the monthly snake draft can start.</p></div>{selectedLeague?.isCreator?<button className="primary-button" disabled={busy||selectedLeague.memberCount<4} onClick={()=>void act(()=>startFantasyDraft(client,selectedId,new Date().toISOString().slice(0,7)+"-01"))}>Start this month’s draft</button>:null}</section>:<>
        <section className="draft-status"><span><small>Status</small><b>{season.status}</b></span><span><small>Pick</small><b>{season.currentPick}</b></span><span><small>On the clock</small><b>{overview?.members.find(x=>x.userId===pickerId)?.displayName||"Draft complete"}</b></span><span><small>Deadline</small><b>{season.pickDeadline?new Date(season.pickDeadline).toLocaleString():"—"}</b></span></section>
        {season.status==="drafting"?<section className="draft-room"><div className="draft-board"><h2>Pick history</h2>{overview?.picks.length?<ol>{overview.picks.map(p=><li key={p.pickNumber}><span>{p.pickNumber}</span><b>{p.snackName}</b><small>{p.category}{p.wasAutoPick?" · auto-pick":""}</small></li>)}</ol>:<p className="empty-state">The first manager is on the clock.</p>}</div><div className="draft-actions"><h2>{myTurn?"You’re on the clock":"Build your auto-pick queue"}</h2><form onSubmit={submitSearch}><label>Search snacks<input type="search" value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="secondary-button compact" disabled={busy||query.trim().length<3}>{busy?"Searching…":"Search"}</button></form>{results.length?<ul className="fantasy-search">{results.map((s,i)=><li key={s.id||s.barcode||`${s.name}-${i}`}><span><b>{s.name}</b><small>{s.category}</small></span><button className="text-button" disabled={busy} onClick={()=>void choose(s,myTurn?"pick":"preference")}>{myTurn?"Draft":"Add to queue"}</button></li>)}</ul>:null}{preferences.length?<div className="preference-queue"><h3>Auto-pick order</h3><ol>{preferences.map(s=><li key={s.id}>{s.name}</li>)}</ol><button className="secondary-button" disabled={busy} onClick={()=>void act(()=>setFantasyPreferences(client,season.id,preferences.map(x=>x.id!)))}>Save queue</button></div>:null}</div></section>:<ActiveSeason overview={overview!} currentUserId={currentUserId} query={query} setQuery={setQuery} submitSearch={submitSearch} results={results} waiverOut={waiverOut} setWaiverOut={setWaiverOut} busy={busy} choose={choose}/>}
      </>}</>}
  </div>;
}

function LockedFantasy({feature}:{feature:FantasyFeatureState}){const metrics=[{label:"Pilot weeks",value:`${feature.weeksObserved}/4`,pass:feature.weeksObserved>=4},{label:"Daily active",value:String(feature.dailyActiveUsers),pass:feature.dailyActiveUsers>5},{label:"Full bracket",value:feature.fullBracketParticipation?"Complete":"Waiting",pass:feature.fullBracketParticipation},{label:"User growth",value:feature.weeklyUserGrowth?"Growing":"Waiting",pass:feature.weeklyUserGrowth},{label:"Logs / week",value:String(feature.averageLogsPerUserWeek),pass:feature.averageLogsPerUserWeek>=3}];return <div className="fantasy-screen locked-fantasy"><header className="fantasy-hero"><p className="section-label">Fantasy league</p><h1>Earn the unlock.</h1><p>The draft room stays closed until Snack Squad proves four weeks of healthy daily participation.</p></header><div className="pilot-meter">{metrics.map(m=><div className={m.pass?"passed":""} key={m.label}><span>{m.label}</span><b>{m.value}</b><small>{m.pass?"Ready":"Not yet"}</small></div>)}</div><p className="lock-note">A moderator reviews these signals before enabling fantasy. The gate never opens automatically.</p></div>}

function ActiveSeason({overview,currentUserId,query,setQuery,submitSearch,results,waiverOut,setWaiverOut,busy,choose}:{overview:FantasyOverview;currentUserId:string;query:string;setQuery:(x:string)=>void;submitSearch:(event:FormEvent)=>Promise<void>;results:SnackMetadata[];waiverOut:string;setWaiverOut:(x:string)=>void;busy:boolean;choose:(s:SnackMetadata,m:"waiver")=>Promise<void>}){const mine=overview.roster.filter(x=>x.userId===currentUserId);return <section className="active-fantasy"><div className="standings"><h2>Standings</h2><ol>{overview.standings.map((s,i)=><li key={s.userId}><span>{i+1}</span><b>{overview.members.find(m=>m.userId===s.userId)?.displayName}</b><strong>{s.points}</strong></li>)}</ol></div><div className="my-roster"><h2>Your roster</h2><ul>{mine.map(x=><li key={x.category}><span><b>{x.snackName}</b><small>{x.category}</small></span><strong>{overview.standings.find(s=>s.userId===currentUserId)?.points||0}</strong></li>)}</ul><h3>Friday waiver</h3><label>Replace<select value={waiverOut} onChange={e=>setWaiverOut(e.target.value)}><option value="">Choose roster snack</option>{mine.map(x=><option value={x.snackId} key={x.snackId}>{x.snackName}</option>)}</select></label><form onSubmit={submitSearch}><label>Find same-category replacement<input type="search" value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="secondary-button compact" disabled={busy||query.trim().length<3}>{busy?"Searching…":"Search"}</button></form>{results.map((s,i)=><button className="text-button" disabled={busy} key={s.id||i} onClick={()=>void choose(s,"waiver")}>Claim {s.name}</button>)}</div></section>}
